# Site
name: "GrupyRN"
title: "GrupyRN"
description: "Blog da comunidade GrupyRN"
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
google_analytics: "G-ZD4RGBGFPK"
disqus: "demowebsite"
# mailchimp-list:
include: ["_pages"]
permalink: /:title/
comments: false
authors:
  itepifanio:
    name: Ítalo Epifânio
    display_name: Ítalo Epifânio
    email: italoepifaniols@gmail.com
    web: https://itepifanio.github.io
    twitter: https://twitter.com/itepifanio
    description: "Machine Leaning Engineer"

  mayperp:
    name: Mayra Perpétua
    display_name: Mayra Perpétua
    email: mayraperpetua.tech@gmail.com
    web: https://github.com/MayraPerpetua
    twitter: https://twitter.com/perpetua_tech
    description: "UX UI Designer e Desenvolvedora Web"

  allythy:
    name: Allythy
    display_name: Allythy
    web: https://allythy.github.io/
    description: "Desenvolvedor Web. Sempre aceito um sorvete"

  igorafm:
    name: Igor
    display_name: Igor Macedo
    web: https://github.com/igorafm/
    description: "Entusiasta da inovação, do Direito, Python e NLP"

  jhonatacaiob:
    name: Jhonata
    display_name: Jhonata Medeiros
    web: https://github.com/jhonatacaiob
    description: "Desenvolvedor web e Pythonista"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, vendor]
